format = """
[](#9A348E)\
$os$username$sudo\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c$rust$golang$java$python\
[](fg:#86BBD8 bg:#06969A)\
$docker_context$conda\
[](fg:#06969A bg:#33658A)\
$cmd_duration$time\
[ ](fg:#33658A)\
$line_break$env_var$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[ $user ]($style)'
disabled = false

[sudo]
disabled = false
style = "bg:#9A348E"
symbol = "🧙"
format = '[as $symbol ]($style)'

# Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
# error_symbol = "[➜](red)"
# vimcmd_symbol = '[V](bold green)'

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = false # Disabled by default

[os.symbols]
Arch = "󰣇"

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#86BBD8"
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = 'python'
version_format = 'v${raw}'

[conda]
disabled = false
ignore_base = false
symbol = "🅒 "
format = '[ $symbol$environment ](bg:#06969A)'

[time]
disabled = false
# time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[  $time ]($style)'


[cmd_duration]
min_time = 100
format = '[ took [$duration](bold yellow bg:#33658A)](bg:#33658A)'